### ISSUE TITLE
Try out no-panic

### ISSUE THREAD

**Issue by fasterthanlime** [rust-compress/rc-zip#1]
https://crates.io/crates/no-panic

Codebase has a bunch of expects/unwraps for now, until we figure out all the error handling.

**Comment by Geal** [comment]
the trick behind `no-panic` and the older `dont_panic` is extremely cool. Coercing the compiler into generating a linker error if there's a possibility of panic

**Comment by fasterthanlime** [comment]
Just tried it:

![image](https://user-images.githubusercontent.com/7998310/61035656-dc383000-a3c7-11e9-96a9-e113cf7b7ffb.png)

I'm not able to say where it comes from yet

**Comment by Geal** [comment]
yup it will only tells you it can panic, not where it is

**Comment by Geal** [comment]
does it still show that when you build in release mode? Slice indexing can panic in debug mode, but the bounds checks are often removed in release. And nom does a lot of slice indexing

**Comment by fasterthanlime** [comment]
I tried to set this in Cargo.toml:

```
[profile.test]
opt-level = 1
```

(also tried 2, 3) but it was still unhappy. It did seem like it was somewhere in a nom parser, I tried to narrow it down a little.

**Comment by fasterthanlime** [comment]
Closing for now, feel free to re-open if anyone gets it working.
