### ISSUE TITLE
Reading a file entry (newbie question) - trying to use the examples

### ISSUE THREAD

**Issue by bivald** [rust-compress/rc-zip#14]
Hi,

Sorry this is a bit of a newbie question - I'm trying to follow the read file examples but I can't seem to get it to work. I'm trying to open a zip file, loop through the entries and pass the buffer of the file I want to quick xml (without writing the file to disk). Opening and looping is super simple, but I fail at passing the buffer.

I tried:
```
let entry_reader = c
                            .entry
                            .sync_reader(|offset| positioned_io::Cursor::new_pos(&zipfile, offset));
```

But it says that sync_reader method doesn't exist. 

I tried the other example:
```
rc_zip::reader::sync::EntryReader::new(sl.entry, |offset| {
                            positioned_io::Cursor::new_pos(&zipfile, offset)
                        })
                        .read_to_string(&mut target)
                        .unwrap();
```

But it says that the reader is a private method.

The closest I come is:

```
let entry_reader = c.entry.reader(|offset| positioned_io::Cursor::new_pos(&zipfile, offset));
```

Which I think gives me a proper entry_reader, but I can't seem to figure out how to turn this into a Buffer so quick xml can read it. Or figure out how to read it at all.

This is all probably explained in the crates documentation but I'm still at the point where the automatically generated documentation is a bit greek to me :) 

This is how I normally read a buffer in quick xml:

```
let xml_file = File::open(filepath)?;
let buffer = BufReader::new(xml_file);
let mut reader = Reader::from_reader(buffer);
let mut buf = Vec::new();
```

Any help will be greatly appreciated. Also, to put my money where my mouth is I will send anyone who helps me a beer tip via PayPal

**Comment by mbrubeck** [comment]
Both the library and the sample code have changed substantially since this package was last published to crates.io.  You can find sample code and source code for the last published version here:

https://github.com/rust-compress/rc-zip/tree/v0.0.1

**Comment by bivald** [comment]
Thank you @mbrubeck that explains everything, sorry to bother you :)
