### ISSUE TITLE
Half sentence in readme

### ISSUE THREAD

**Issue by senden9** [rust-compress/rc-zip#2]
[README.md line 74](https://github.com/rust-compress/rc-zip/blame/5bc34a8c4bc6d167116ea3c3376ea01ef7358487/README.md#L74) contains this half sentence:

> Due to the nature of the zip format, `ArchiveReader` needs its own

It's like a cliffhanger :D

**Comment by fasterthanlime** [comment]
Ah yes, just before I decided the rustdoc comments were a better place to explain that.
